version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - "../test-perfect-panel:/var/www/test-perfect-panel"
    ports:
      - '8000:80'
